# coding: utf-8

"""
    Nightscout API

    Own your DData with the Nightscout API  # noqa: E501

    OpenAPI spec version: 14.2.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Optime(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'ts': 'str',
        't': 'int'
    }

    attribute_map = {
        'ts': 'ts',
        't': 't'
    }

    def __init__(self, ts=None, t=None):  # noqa: E501
        """Optime - a model defined in Swagger"""  # noqa: E501
        self._ts = None
        self._t = None
        self.discriminator = None
        if ts is not None:
            self.ts = ts
        if t is not None:
            self.t = t

    @property
    def ts(self):
        """Gets the ts of this Optime.  # noqa: E501

        Time the operation started  # noqa: E501

        :return: The ts of this Optime.  # noqa: E501
        :rtype: str
        """
        return self._ts

    @ts.setter
    def ts(self, ts):
        """Sets the ts of this Optime.

        Time the operation started  # noqa: E501

        :param ts: The ts of this Optime.  # noqa: E501
        :type: str
        """

        self._ts = ts

    @property
    def t(self):
        """Gets the t of this Optime.  # noqa: E501

        Time the operation took to complete  # noqa: E501

        :return: The t of this Optime.  # noqa: E501
        :rtype: int
        """
        return self._t

    @t.setter
    def t(self, t):
        """Sets the t of this Optime.

        Time the operation took to complete  # noqa: E501

        :param t: The t of this Optime.  # noqa: E501
        :type: int
        """

        self._t = t

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Optime, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Optime):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
