# coding: utf-8

"""
    Nightscout API

    Own your DData with the Nightscout API  # noqa: E501

    OpenAPI spec version: 14.2.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Pumpstatus(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'status': 'str',
        'bolusing': 'bool',
        'suspended': 'bool',
        'timestamp': 'str'
    }

    attribute_map = {
        'status': 'status',
        'bolusing': 'bolusing',
        'suspended': 'suspended',
        'timestamp': 'timestamp'
    }

    def __init__(self, status=None, bolusing=None, suspended=None, timestamp=None):  # noqa: E501
        """Pumpstatus - a model defined in Swagger"""  # noqa: E501
        self._status = None
        self._bolusing = None
        self._suspended = None
        self._timestamp = None
        self.discriminator = None
        if status is not None:
            self.status = status
        if bolusing is not None:
            self.bolusing = bolusing
        if suspended is not None:
            self.suspended = suspended
        if timestamp is not None:
            self.timestamp = timestamp

    @property
    def status(self):
        """Gets the status of this Pumpstatus.  # noqa: E501

        Pump Status String  # noqa: E501

        :return: The status of this Pumpstatus.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this Pumpstatus.

        Pump Status String  # noqa: E501

        :param status: The status of this Pumpstatus.  # noqa: E501
        :type: str
        """

        self._status = status

    @property
    def bolusing(self):
        """Gets the bolusing of this Pumpstatus.  # noqa: E501

        Is Pump Bolusing  # noqa: E501

        :return: The bolusing of this Pumpstatus.  # noqa: E501
        :rtype: bool
        """
        return self._bolusing

    @bolusing.setter
    def bolusing(self, bolusing):
        """Sets the bolusing of this Pumpstatus.

        Is Pump Bolusing  # noqa: E501

        :param bolusing: The bolusing of this Pumpstatus.  # noqa: E501
        :type: bool
        """

        self._bolusing = bolusing

    @property
    def suspended(self):
        """Gets the suspended of this Pumpstatus.  # noqa: E501

        Is Pump Suspended  # noqa: E501

        :return: The suspended of this Pumpstatus.  # noqa: E501
        :rtype: bool
        """
        return self._suspended

    @suspended.setter
    def suspended(self, suspended):
        """Sets the suspended of this Pumpstatus.

        Is Pump Suspended  # noqa: E501

        :param suspended: The suspended of this Pumpstatus.  # noqa: E501
        :type: bool
        """

        self._suspended = suspended

    @property
    def timestamp(self):
        """Gets the timestamp of this Pumpstatus.  # noqa: E501

        dateString, prefer ISO `8601`  # noqa: E501

        :return: The timestamp of this Pumpstatus.  # noqa: E501
        :rtype: str
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp):
        """Sets the timestamp of this Pumpstatus.

        dateString, prefer ISO `8601`  # noqa: E501

        :param timestamp: The timestamp of this Pumpstatus.  # noqa: E501
        :type: str
        """

        self._timestamp = timestamp

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Pumpstatus, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Pumpstatus):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
