# coding: utf-8

"""
    Nightscout API

    Own your DData with the Nightscout API  # noqa: E501

    OpenAPI spec version: 14.2.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Pumpbattery(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'status': 'str',
        'voltage': 'float'
    }

    attribute_map = {
        'status': 'status',
        'voltage': 'voltage'
    }

    def __init__(self, status=None, voltage=None):  # noqa: E501
        """Pumpbattery - a model defined in Swagger"""  # noqa: E501
        self._status = None
        self._voltage = None
        self.discriminator = None
        if status is not None:
            self.status = status
        if voltage is not None:
            self.voltage = voltage

    @property
    def status(self):
        """Gets the status of this Pumpbattery.  # noqa: E501

        Pump Battery Status String  # noqa: E501

        :return: The status of this Pumpbattery.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this Pumpbattery.

        Pump Battery Status String  # noqa: E501

        :param status: The status of this Pumpbattery.  # noqa: E501
        :type: str
        """

        self._status = status

    @property
    def voltage(self):
        """Gets the voltage of this Pumpbattery.  # noqa: E501

        Pump Battery Voltage Level  # noqa: E501

        :return: The voltage of this Pumpbattery.  # noqa: E501
        :rtype: float
        """
        return self._voltage

    @voltage.setter
    def voltage(self, voltage):
        """Sets the voltage of this Pumpbattery.

        Pump Battery Voltage Level  # noqa: E501

        :param voltage: The voltage of this Pumpbattery.  # noqa: E501
        :type: float
        """

        self._voltage = voltage

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Pumpbattery, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Pumpbattery):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
