# coding: utf-8

"""
    Nightscout API

    Own your DData with the Nightscout API  # noqa: E501

    OpenAPI spec version: 14.2.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six
from nightscout_python_client.api.util import ALL_PARAMS, parse_query_params

from nightscout_python_client.api_client import ApiClient


class EntriesApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def add_entries(self, body, **kwargs):  # noqa: E501
        """Add new entries.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.add_entries(body, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param list[Entry] body: Entries to be uploaded. (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.add_entries_with_http_info(body, **kwargs)  # noqa: E501
        else:
            (data) = self.add_entries_with_http_info(body, **kwargs)  # noqa: E501
            return data

    def add_entries_with_http_info(self, body, **kwargs):  # noqa: E501
        """Add new entries.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.add_entries_with_http_info(body, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param list[Entry] body: Entries to be uploaded. (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method add_entries" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'body' is set
        if ('body' not in params or
                params['body'] is None):
            raise ValueError("Missing the required parameter `body` when calling `add_entries`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json', 'text/plain'])  # noqa: E501

        # Authentication setting
        auth_settings = ['api_secret', 'jwtoken', 'token_in_url']  # noqa: E501

        return self.api_client.call_api(
            '/entries', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def echo_storage_spec_get(self, storage, spec, **kwargs):  # noqa: E501
        """View generated Mongo Query object  # noqa: E501

        Information about the mongo query object created by the query.   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.echo_storage_spec_get(storage, spec, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str storage: `entries`, or `treatments` to select the storage layer.  (required)
        :param str spec: entry id, such as `55cf81bc436037528ec75fa5` or a type filter such as `sgv`, `mbg`, etc. This parameter is optional.  (required)
        :param str find: The query used to find entries, support nested query syntax, for example `find[dateString][$gte]=2015-08-27`.  All find parameters are interpreted as strings. 
        :param float count: Number of entries to return.
        :return: MongoQuery
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.echo_storage_spec_get_with_http_info(storage, spec, **kwargs)  # noqa: E501
        else:
            (data) = self.echo_storage_spec_get_with_http_info(storage, spec, **kwargs)  # noqa: E501
            return data

    def echo_storage_spec_get_with_http_info(self, storage, spec, **kwargs):  # noqa: E501
        """View generated Mongo Query object  # noqa: E501

        Information about the mongo query object created by the query.   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.echo_storage_spec_get_with_http_info(storage, spec, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str storage: `entries`, or `treatments` to select the storage layer.  (required)
        :param str spec: entry id, such as `55cf81bc436037528ec75fa5` or a type filter such as `sgv`, `mbg`, etc. This parameter is optional.  (required)
        :param str find: The query used to find entries, support nested query syntax, for example `find[dateString][$gte]=2015-08-27`.  All find parameters are interpreted as strings. 
        :param float count: Number of entries to return.
        :return: MongoQuery
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['storage', 'spec', 'find', 'count']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method echo_storage_spec_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'storage' is set
        if ('storage' not in params or
                params['storage'] is None):
            raise ValueError("Missing the required parameter `storage` when calling `echo_storage_spec_get`")  # noqa: E501
        # verify the required parameter 'spec' is set
        if ('spec' not in params or
                params['spec'] is None):
            raise ValueError("Missing the required parameter `spec` when calling `echo_storage_spec_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'storage' in params:
            path_params['storage'] = params['storage']  # noqa: E501
        if 'spec' in params:
            path_params['spec'] = params['spec']  # noqa: E501

        # query_params = []
        # if 'find' in params:
        #     query_params.append(('find', params['find']))  # noqa: E501
        # if 'count' in params:
        #     query_params.append(('count', params['count']))  # noqa: E501
        query_params = parse_query_params(params)

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['api_secret', 'jwtoken', 'token_in_url']  # noqa: E501

        return self.api_client.call_api(
            '/echo/{storage}/{spec}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='MongoQuery',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def entries_get(self, **kwargs):  # noqa: E501
        """All Entries matching query  # noqa: E501

        The Entries endpoint returns information about the Nightscout entries.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.entries_get(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str find: The query used to find entries, support nested query syntax, for example `find[dateString][$gte]=2015-08-27`.  All find parameters are interpreted as strings.
        :param float count: Number of entries to return.
        :return: Entries
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.entries_get_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.entries_get_with_http_info(**kwargs)  # noqa: E501
            return data

    def entries_get_with_http_info(self, **kwargs):  # noqa: E501
        """All Entries matching query  # noqa: E501

        The Entries endpoint returns information about the Nightscout entries.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.entries_get_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str find: The query used to find entries, support nested query syntax, for example `find[dateString][$gte]=2015-08-27`.  All find parameters are interpreted as strings.
        :param float count: Number of entries to return.
        :return: Entries
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['findDateGte', 'findDateLte', 'count']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method entries_get" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        # query_params = []
        # # if 'find' in params:
        # #     query_params.append(('find', params['find']))  # noqa: E501
        # if 'findDateGte' in params:
        #     query_params.append(('find[date][$gte]', params['findDateGte']))  # noqa: E501
        # if 'findDateLte' in params:
        #     query_params.append(('find[date][$lte]', params['findDateLte']))  # noqa: E501
        # if 'count' in params:
        #     query_params.append(('count', params['count']))  # noqa: E501
        query_params = parse_query_params(params)

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['api_secret', 'jwtoken', 'token_in_url']  # noqa: E501

        return self.api_client.call_api(
            '/entries', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='Entries',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def entries_spec_get(self, spec, **kwargs):  # noqa: E501
        """All Entries matching query  # noqa: E501

        The Entries endpoint returns information about the Nightscout entries.   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.entries_spec_get(spec, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str spec: entry id, such as `55cf81bc436037528ec75fa5` or a type filter such as `sgv`, `mbg`, etc.  (required)
        :param str find: The query used to find entries, support nested query syntax, for example `find[dateString][$gte]=2015-08-27`.  All find parameters are interpreted as strings. 
        :param float count: Number of entries to return.
        :return: Entries
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.entries_spec_get_with_http_info(spec, **kwargs)  # noqa: E501
        else:
            (data) = self.entries_spec_get_with_http_info(spec, **kwargs)  # noqa: E501
            return data

    def entries_spec_get_with_http_info(self, spec, **kwargs):  # noqa: E501
        """All Entries matching query  # noqa: E501

        The Entries endpoint returns information about the Nightscout entries.   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.entries_spec_get_with_http_info(spec, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str spec: entry id, such as `55cf81bc436037528ec75fa5` or a type filter such as `sgv`, `mbg`, etc.  (required)
        :param str find: The query used to find entries, support nested query syntax, for example `find[dateString][$gte]=2015-08-27`.  All find parameters are interpreted as strings. 
        :param float count: Number of entries to return.
        :return: Entries
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ALL_PARAMS # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method entries_spec_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'spec' is set
        if ('spec' not in params or
                params['spec'] is None):
            raise ValueError("Missing the required parameter `spec` when calling `entries_spec_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'spec' in params:
            path_params['spec'] = params['spec']  # noqa: E501

        # query_params = []
        # if 'find' in params:
        #     query_params.append(('find', params['find']))  # noqa: E501
        # if 'count' in params:
        #     query_params.append(('count', params['count']))  # noqa: E501

        query_params = parse_query_params(params)

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['api_secret', 'jwtoken', 'token_in_url']  # noqa: E501

        return self.api_client.call_api(
            '/entries/{spec}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='Entries',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def remove(self, **kwargs):  # noqa: E501
        """Delete entries matching query.  # noqa: E501

        Remove entries, same search syntax as GET.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.remove(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str find: The query used to find entries, support nested query syntax, for example `find[dateString][$gte]=2015-08-27`.  All find parameters are interpreted as strings.
        :param float count: Number of entries to return.
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.remove_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.remove_with_http_info(**kwargs)  # noqa: E501
            return data

    def remove_with_http_info(self, **kwargs):  # noqa: E501
        """Delete entries matching query.  # noqa: E501

        Remove entries, same search syntax as GET.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.remove_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str find: The query used to find entries, support nested query syntax, for example `find[dateString][$gte]=2015-08-27`.  All find parameters are interpreted as strings.
        :param float count: Number of entries to return.
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ALL_PARAMS # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method remove" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        # query_params = []
        # if 'find' in params:
        #     query_params.append(('find', params['find']))  # noqa: E501
        # if 'count' in params:
        #     query_params.append(('count', params['count']))  # noqa: E501
        query_params = parse_query_params(params)

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = ['api_secret', 'jwtoken', 'token_in_url']  # noqa: E501

        return self.api_client.call_api(
            '/entries', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def slice_storage_field_type_prefix_regex_get(self, storage, field, type, prefix, regex, **kwargs):  # noqa: E501
        """All Entries matching query  # noqa: E501

        The Entries endpoint returns information about the Nightscout entries.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.slice_storage_field_type_prefix_regex_get(storage, field, type, prefix, regex, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str storage: Prefix to use in constructing a prefix-based regex, default is `entries`. (required)
        :param str field: Name of the field to use Regex against in query object, default is `dateString`. (required)
        :param str type: The type field to search against, default is sgv. (required)
        :param str prefix: Prefix to use in constructing a prefix-based regex. (required)
        :param str regex: Tail part of regexp to use in expanding/construccting a query object. Regexp also has bash-style brace and glob expansion applied to it, creating ways to search for modal times of day, perhaps using something like this syntax: `T{15..17}:.*`, this would search for all records from 3pm to 5pm.  (required)
        :param str find: The query used to find entries, support nested query syntax, for example `find[dateString][$gte]=2015-08-27`.  All find parameters are interpreted as strings. 
        :param float count: Number of entries to return.
        :return: Entries
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.slice_storage_field_type_prefix_regex_get_with_http_info(storage, field, type, prefix, regex, **kwargs)  # noqa: E501
        else:
            (data) = self.slice_storage_field_type_prefix_regex_get_with_http_info(storage, field, type, prefix, regex, **kwargs)  # noqa: E501
            return data

    def slice_storage_field_type_prefix_regex_get_with_http_info(self, storage, field, type, prefix, regex, **kwargs):  # noqa: E501
        """All Entries matching query  # noqa: E501

        The Entries endpoint returns information about the Nightscout entries.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.slice_storage_field_type_prefix_regex_get_with_http_info(storage, field, type, prefix, regex, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str storage: Prefix to use in constructing a prefix-based regex, default is `entries`. (required)
        :param str field: Name of the field to use Regex against in query object, default is `dateString`. (required)
        :param str type: The type field to search against, default is sgv. (required)
        :param str prefix: Prefix to use in constructing a prefix-based regex. (required)
        :param str regex: Tail part of regexp to use in expanding/construccting a query object. Regexp also has bash-style brace and glob expansion applied to it, creating ways to search for modal times of day, perhaps using something like this syntax: `T{15..17}:.*`, this would search for all records from 3pm to 5pm.  (required)
        :param str find: The query used to find entries, support nested query syntax, for example `find[dateString][$gte]=2015-08-27`.  All find parameters are interpreted as strings. 
        :param float count: Number of entries to return.
        :return: Entries
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['storage', 'field', 'type', 'prefix', 'regex', 'find', 'count']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method slice_storage_field_type_prefix_regex_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'storage' is set
        if ('storage' not in params or
                params['storage'] is None):
            raise ValueError("Missing the required parameter `storage` when calling `slice_storage_field_type_prefix_regex_get`")  # noqa: E501
        # verify the required parameter 'field' is set
        if ('field' not in params or
                params['field'] is None):
            raise ValueError("Missing the required parameter `field` when calling `slice_storage_field_type_prefix_regex_get`")  # noqa: E501
        # verify the required parameter 'type' is set
        if ('type' not in params or
                params['type'] is None):
            raise ValueError("Missing the required parameter `type` when calling `slice_storage_field_type_prefix_regex_get`")  # noqa: E501
        # verify the required parameter 'prefix' is set
        if ('prefix' not in params or
                params['prefix'] is None):
            raise ValueError("Missing the required parameter `prefix` when calling `slice_storage_field_type_prefix_regex_get`")  # noqa: E501
        # verify the required parameter 'regex' is set
        if ('regex' not in params or
                params['regex'] is None):
            raise ValueError("Missing the required parameter `regex` when calling `slice_storage_field_type_prefix_regex_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'storage' in params:
            path_params['storage'] = params['storage']  # noqa: E501
        if 'field' in params:
            path_params['field'] = params['field']  # noqa: E501
        if 'type' in params:
            path_params['type'] = params['type']  # noqa: E501
        if 'prefix' in params:
            path_params['prefix'] = params['prefix']  # noqa: E501
        if 'regex' in params:
            path_params['regex'] = params['regex']  # noqa: E501

        # query_params = []
        # if 'find' in params:
        #     query_params.append(('find', params['find']))  # noqa: E501
        # if 'count' in params:
        #     query_params.append(('count', params['count']))  # noqa: E501
        query_params = parse_query_params(params)

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['api_secret', 'jwtoken', 'token_in_url']  # noqa: E501

        return self.api_client.call_api(
            '/slice/{storage}/{field}/{type}/{prefix}/{regex}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='Entries',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def times_echo_prefix_regex_get(self, prefix, regex, **kwargs):  # noqa: E501
        """Echo the query object to be used.  # noqa: E501

        Echo debug information about the query object constructed.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.times_echo_prefix_regex_get(prefix, regex, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str prefix: Prefix to use in constructing a prefix-based regex. (required)
        :param str regex: Tail part of regexp to use in expanding/construccting a query object. Regexp also has bash-style brace and glob expansion applied to it, creating ways to search for modal times of day, perhaps using something like this syntax: `T{15..17}:.*`, this would search for all records from 3pm to 5pm.  (required)
        :param str find: The query used to find entries, support nested query syntax, for example `find[dateString][$gte]=2015-08-27`.  All find parameters are interpreted as strings.
        :param float count: Number of entries to return.
        :return: MongoQuery
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.times_echo_prefix_regex_get_with_http_info(prefix, regex, **kwargs)  # noqa: E501
        else:
            (data) = self.times_echo_prefix_regex_get_with_http_info(prefix, regex, **kwargs)  # noqa: E501
            return data

    def times_echo_prefix_regex_get_with_http_info(self, prefix, regex, **kwargs):  # noqa: E501
        """Echo the query object to be used.  # noqa: E501

        Echo debug information about the query object constructed.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.times_echo_prefix_regex_get_with_http_info(prefix, regex, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str prefix: Prefix to use in constructing a prefix-based regex. (required)
        :param str regex: Tail part of regexp to use in expanding/construccting a query object. Regexp also has bash-style brace and glob expansion applied to it, creating ways to search for modal times of day, perhaps using something like this syntax: `T{15..17}:.*`, this would search for all records from 3pm to 5pm.  (required)
        :param str find: The query used to find entries, support nested query syntax, for example `find[dateString][$gte]=2015-08-27`.  All find parameters are interpreted as strings.
        :param float count: Number of entries to return.
        :return: MongoQuery
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['prefix', 'regex', 'find', 'count']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method times_echo_prefix_regex_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'prefix' is set
        if ('prefix' not in params or
                params['prefix'] is None):
            raise ValueError("Missing the required parameter `prefix` when calling `times_echo_prefix_regex_get`")  # noqa: E501
        # verify the required parameter 'regex' is set
        if ('regex' not in params or
                params['regex'] is None):
            raise ValueError("Missing the required parameter `regex` when calling `times_echo_prefix_regex_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'prefix' in params:
            path_params['prefix'] = params['prefix']  # noqa: E501
        if 'regex' in params:
            path_params['regex'] = params['regex']  # noqa: E501

        # query_params = []
        # if 'find' in params:
        #     query_params.append(('find', params['find']))  # noqa: E501
        # if 'count' in params:
        #     query_params.append(('count', params['count']))  # noqa: E501
        query_params = parse_query_params(params)

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['api_secret', 'jwtoken', 'token_in_url']  # noqa: E501

        return self.api_client.call_api(
            '/times/echo/{prefix}/{regex}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='MongoQuery',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def times_prefix_regex_get(self, prefix, regex, **kwargs):  # noqa: E501
        """All Entries matching query  # noqa: E501

        The Entries endpoint returns information about the Nightscout entries.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.times_prefix_regex_get(prefix, regex, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str prefix: Prefix to use in constructing a prefix-based regex. (required)
        :param str regex: Tail part of regexp to use in expanding/construccting a query object. Regexp also has bash-style brace and glob expansion applied to it, creating ways to search for modal times of day, perhaps using something like this syntax: `T{15..17}:.*`, this would search for all records from 3pm to 5pm.  (required)
        :param str find: The query used to find entries, support nested query syntax, for example `find[dateString][$gte]=2015-08-27`.  All find parameters are interpreted as strings.
        :param float count: Number of entries to return.
        :return: Entries
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.times_prefix_regex_get_with_http_info(prefix, regex, **kwargs)  # noqa: E501
        else:
            (data) = self.times_prefix_regex_get_with_http_info(prefix, regex, **kwargs)  # noqa: E501
            return data

    def times_prefix_regex_get_with_http_info(self, prefix, regex, **kwargs):  # noqa: E501
        """All Entries matching query  # noqa: E501

        The Entries endpoint returns information about the Nightscout entries.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.times_prefix_regex_get_with_http_info(prefix, regex, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str prefix: Prefix to use in constructing a prefix-based regex. (required)
        :param str regex: Tail part of regexp to use in expanding/construccting a query object. Regexp also has bash-style brace and glob expansion applied to it, creating ways to search for modal times of day, perhaps using something like this syntax: `T{15..17}:.*`, this would search for all records from 3pm to 5pm.  (required)
        :param str find: The query used to find entries, support nested query syntax, for example `find[dateString][$gte]=2015-08-27`.  All find parameters are interpreted as strings.
        :param float count: Number of entries to return.
        :return: Entries
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['prefix', 'regex', 'find', 'count']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method times_prefix_regex_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'prefix' is set
        if ('prefix' not in params or
                params['prefix'] is None):
            raise ValueError("Missing the required parameter `prefix` when calling `times_prefix_regex_get`")  # noqa: E501
        # verify the required parameter 'regex' is set
        if ('regex' not in params or
                params['regex'] is None):
            raise ValueError("Missing the required parameter `regex` when calling `times_prefix_regex_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'prefix' in params:
            path_params['prefix'] = params['prefix']  # noqa: E501
        if 'regex' in params:
            path_params['regex'] = params['regex']  # noqa: E501

        # query_params = []
        # if 'find' in params:
        #     query_params.append(('find', params['find']))  # noqa: E501
        # if 'count' in params:
        #     query_params.append(('count', params['count']))  # noqa: E501
        query_params = parse_query_params(params)

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['api_secret', 'jwtoken', 'token_in_url']  # noqa: E501

        return self.api_client.call_api(
            '/times/{prefix}/{regex}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='Entries',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
