# coding: utf-8

"""
    Nightscout API

    Own your DData with the Nightscout API  # noqa: E501

    OpenAPI spec version: 14.2.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import nightscout_python_client
from nightscout_python_client.api.profile_api import ProfileApi  # noqa: E501
from nightscout_python_client.rest import ApiException


class TestProfileApi(unittest.TestCase):
    """ProfileApi unit test stubs"""

    def setUp(self):
        self.api = ProfileApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_profile_get(self):
        """Test case for profile_get

        Profile  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
