# coding: utf-8

"""
    Nightscout API

    Own your DData with the Nightscout API  # noqa: E501

    OpenAPI spec version: 14.2.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import nightscout_python_client
from nightscout_python_client.api.debug_api import DebugApi  # noqa: E501
from nightscout_python_client.rest import ApiException


class TestDebugApi(unittest.TestCase):
    """DebugApi unit test stubs"""

    def setUp(self):
        self.api = DebugApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_echo_storage_spec_get(self):
        """Test case for echo_storage_spec_get

        View generated Mongo Query object  # noqa: E501
        """
        pass

    def test_times_echo_prefix_regex_get(self):
        """Test case for times_echo_prefix_regex_get

        Echo the query object to be used.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
