# coding: utf-8

"""
    Nightscout API

    Own your DData with the Nightscout API  # noqa: E501

    OpenAPI spec version: 14.2.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import nightscout_python_client
from nightscout_python_client.models.treatment import Treatment  # noqa: E501
from nightscout_python_client.rest import ApiException


class TestTreatment(unittest.TestCase):
    """Treatment unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTreatment(self):
        """Test Treatment"""
        # FIXME: construct object with mandatory attributes with example values
        # model = nightscout_python_client.models.treatment.Treatment()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
