# coding: utf-8

"""
    Nightscout API

    Own your DData with the Nightscout API  # noqa: E501

    OpenAPI spec version: 14.2.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import nightscout_python_client
from nightscout_python_client.api.entries_api import EntriesApi  # noqa: E501
from nightscout_python_client.rest import ApiException


class TestEntriesApi(unittest.TestCase):
    """EntriesApi unit test stubs"""

    def setUp(self):
        self.api = EntriesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_entries(self):
        """Test case for add_entries

        Add new entries.  # noqa: E501
        """
        pass

    def test_echo_storage_spec_get(self):
        """Test case for echo_storage_spec_get

        View generated Mongo Query object  # noqa: E501
        """
        pass

    def test_entries_get(self):
        """Test case for entries_get

        All Entries matching query  # noqa: E501
        """
        pass

    def test_entries_spec_get(self):
        """Test case for entries_spec_get

        All Entries matching query  # noqa: E501
        """
        pass

    def test_remove(self):
        """Test case for remove

        Delete entries matching query.  # noqa: E501
        """
        pass

    def test_slice_storage_field_type_prefix_regex_get(self):
        """Test case for slice_storage_field_type_prefix_regex_get

        All Entries matching query  # noqa: E501
        """
        pass

    def test_times_echo_prefix_regex_get(self):
        """Test case for times_echo_prefix_regex_get

        Echo the query object to be used.  # noqa: E501
        """
        pass

    def test_times_prefix_regex_get(self):
        """Test case for times_prefix_regex_get

        All Entries matching query  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
